name: Build Docker Image for lampa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with the Dockerfile
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Step 2: Clone the external repository containing the app source code
      - name: Clone lampa repository
        run: |
          git clone https://github.com/yumata/lampa-source.git app-source
          ls app-source

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: denadmin/lampa:latest
